---
title: "Final Project - Portfolio"
author: "Tamara Niella"
date: "February 27, 2019"
output: html_document
---


```{r setup, include=FALSE}

library(aod)
library(ggplot2)
library(here)
library(tidyverse)
library(rio)
library(magrittr)
library(skimr)
library(janitor)
library(fastDummies)
library(reshape2)
library(wesanderson)
library(ggridges)

knitr::opts_chunk$set(echo = TRUE)

```

```{r data_wrangling}
#Load data 


dat_int<- import(here("Data", "sim_data_int.csv"))

#making variable names nice 

colnames(dat_int)[1]<- "mindset"

dat_int%<>% janitor::clean_names()

#getting rid of subjects that in the expeirment had some kind of problem (did't complete task well etc), and I am only keeping data from one participant per dyad, since initially, I will only look at answers that dyads answered together (same answer for both participants, I only need one)

dat_dyad<- dat_int%>% 
  filter(problem==0, dyad_part== "A") 

#getting demographic data (for potential methods section)

dat_dem<- dat_int%>% 
  filter(problem==0, gender>0)%>%
  drop_na(age)%>%
  select(gender, age)

mean_age <- mean(dat_dem$age)
sd_age <- sd(dat_dem$age)
sum_fem <- dat_dem %>% 
  filter(gender==2)%>%
  summarize(fem = length(gender))

sum_dem <- dat_dem %>% 
  group_by(gender)%>%
  summarize(gen = length(gender))

#renaming variable value names, changing "treatment for doubt", to improve explanation of study through graphs and analysis

dat_dyad$mindset <-  gsub("Treatment", "Doubt", dat_dyad$mindset)

#coding mindset as factor 

dat_dyad$mindset<-  as.factor(dat_dyad$mindset)
```


```{r plot1}
#I want to see the dyad aswers for agreement (yes or no) for both stories, then I will create a new data set with one variable for agreement, that will iclude agreement for stories one and 2 and another variable that will indicate whether that agreement belongs to story 1 (freedom of speech) or 2 (cyber privacy)

mindset2 <- rep(dat_dyad$mindset, 2)
agreement <- c(dat_dyad$dyad_ag_s1, dat_dyad$dyad_ag_s2)
story <- as.factor(c(rep.int(1,36), rep.int(2,36)))


data<- data.frame(mindset2, agreement, story)

#change values of variable "story", names for numbers (I will only need this if I decide to show the proportions of agreement for the different stories - which is not totally relevant to the results of the study, so I am still debating about it )

data$story <- gsub("1", "Freedom of Speech", data$story)
data$story <- gsub("2", "Cyber Privacy", data$story)

#try 1: summarizing data for plot 1 (version dividing agreement not only per mindset but also per story)

summary2<- data%>% 
  group_by(mindset2, story)%>%
  summarize(prop_agreement =round(mean(agreement),2))
summary2%<>% rename("Mindset" = mindset2)

#try 2: summarizing data for plot 1 (version dividing agreement only per mindset)

summary3<- data%>% 
  group_by(mindset2)%>%
  summarize(prop_agreement =round(mean(agreement),2))

```



